name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup environment variables
        run: |
          echo "VITE_ANALYZE_TONE_URL=${{ secrets.VITE_ANALYZE_TONE_URL }}" >> $GITHUB_ENV
          echo "VITE_CHANGE_TONE_URL=${{ secrets.VITE_CHANGE_TONE_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn vitest

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup environment variables
        run: |
          echo "VITE_ANALYZE_TONE_URL=${{ secrets.VITE_ANALYZE_TONE_URL }}" >> $GITHUB_ENV
          echo "VITE_CHANGE_TONE_URL=${{ secrets.VITE_CHANGE_TONE_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  deploy-docusaurus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Navigate to Docusaurus directory
        run: cd docs # Cambia 'docs' por el directorio donde resides tu documentación si es diferente

      - name: Install dependencies
        run: |
          cd docs # Asegúrate de estar en el directorio correcto de Docusaurus
          yarn install

      - name: Build Docusaurus site
        run: |
          cd docs
          yarn build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          USE_SSH=false yarn deploy

