name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup environment variables
        run: |
          echo "VITE_ANALYZE_TONE_URL=${{ secrets.VITE_ANALYZE_TONE_URL }}" >> $GITHUB_ENV
          echo "VITE_CHANGE_TONE_URL=${{ secrets.VITE_CHANGE_TONE_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn vitest

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

